get real path of filename being transformed
fixes the following error, caused when using sheetify with [the app symlink pattern](https://github.com/substack/browserify-handbook#symlink)

> Error: Cannot find module '../../../sheetify/insert-css' from 'app/components/thing'