pass JSON files through (#85)
before this commit, `require`-ing a JSON file causes

```
SyntaxError: Unexpected token ...
```

this commit

- adds a test for this situation, and
- checks filenames coming in and passes `.json` files through without transformation.
  (`through2` without arguments creates a pass-through stream)

copypasta from: https://github.com/yoshuawuyts/es2020/pull/13